### ISSUE TITLE
Make sure all images set time from NTP servers on boot

### ISSUE THREAD

**Issue by EvaSDK** [moul/image-builder#25]
It looks like ubuntu and docker image at the very least have ntpdate and ntpd installed however ntpdate has no init service and is never called in the boot sequence hence if no other mechanism sets a half-decent date beforehand, a new instance will not have a proper date set, and ntpd will not be able to correct it before long.

Please call ntpdate or sntp explicitely with internal NTP server, early to avoid filesystem timestamps problems, in the boot sequence.

**Comment by moul** [comment]
ubuntu-trusty seems to be ok:

```
root@testram-ubuntu-trusty:~# ps auxww | grep ntp | grep -v grep
ntp       1943  0.0  0.1   4228  2940 ?        Ss   15:09   0:00 /usr/sbin/ntpd -p /var/run/ntpd.pid -g -u 101:104
```

the init script is located at:

```
root@testram-ubuntu-trusty:~# ls -la /etc/init.d/ntp
-rwxr-xr-x 1 root root 1818 Apr  3  2013 /etc/init.d/ntp
```

**Comment by moul** [comment]
ubuntu-utopic seems to be ok too:

```
root@testram-ubuntu-utopic:~# ps auxwww | grep ntp
ntp       2040  0.0  0.1   4588  2864 ?        Ss   15:09   0:00 /usr/sbin/ntpd -p /var/run/ntpd.pid -g -u 100:103
```

the init script is located at:

```
root@testram-ubuntu-utopic:/etc/init.d# ls -la /etc/init.d/ntp
-rwxr-xr-x 1 root root 1818 Apr  3  2013 /etc/init.d/ntp
```

**Comment by moul** [comment]
debian seems to be ok too:

```
root@testram-debian-wheezy:~# ps auxww | grep ntp
ntp       2443  0.0  0.1   4660  2324 ?        Ss   15:26   0:00 /usr/sbin/ntpd -p /var/run/ntpd.pid -g -u 101:103
```

the init script is located at:

```
root@testram-debian-wheezy:/etc/init.d# ls -la /etc/init.d/ntp
-rwxr-xr-x 1 root root 1814 Dec 26  2009 /etc/init.d/ntp
```

**Comment by moul** [comment]
aren't those scripts enough ?
do you think we need an additional call earlier ?

**Comment by EvaSDK** [comment]
ntpd cannot deal with multiple days delta.

This is what occurs on hardware electrical power cycle since RTCs are not battery backed in our case.

We need to call a tool that sets a correctish date on boot, then ntpd can do its job of keeping time as accurate as possible.

**Comment by bchatelard** [comment]
Would it be possible to fetch and set the date from the metadata API ?

**Comment by moul** [comment]
@EvaSDK, what to you think about the idea of @bchatelard ?

It can be a lot faster, also we can add this fix in the initrd

**Comment by EvaSDK** [comment]
You can probably fetch the date from HTTP headers but I don't see the benefit over a tool that is designed to get the time as right as possible in milliseconds.

**Comment by bchatelard** [comment]
I think you should still use ntpd for the accuracy, but you could deal with multiple day delta with the date extracted from the medatada api.

**Comment by bchatelard** [comment]
But this should be simpler and more accurate to call `ntpdate ntp.online.net` on boot.

**Comment by EvaSDK** [comment]
Here is some input from ntpd upstream about sntp vs. ntpdate: http://support.ntp.org/bin/view/Dev/DeprecatingNtpdate

There is no question that the system should run its own NTP time keeping daemon if needed but time should be correct when we start an instance so system does not encouter causality exceptions triggering unwanted fscks, etc. Multiple days delta is a no-no if we want to fix that.

Also note that running ntpd on an instance then restarting on another could lead to incorrect time correction by ntpd since each RTC is unique and drift information stored by ntpd is most likely wrong from one node to another. Imho, cloud users should known about that already but a note in the documentation is still a good idea.

**Comment by moul** [comment]
Moved to: https://github.com/online-labs/initrd/issues/1
