### ISSUE TITLE
[common] Improve ssh-keys init script

### ISSUE THREAD

**Issue by moul** [moul/image-builder#32]
- background the metadata key syncing
- try to speedup the ssh host keys creation

**Comment by aimxhaisse** [comment]
check if keys are generated from /dev/random, try with /dev/urandom

**Comment by moul** [comment]
Tested the key generator of dropbear, the speed looks similar

**Comment by aimxhaisse** [comment]
CPU bound, not blocking on /dev/{u,}random

**Comment by moul** [comment]
Moved to: https://github.com/online-labs/ocs-scripts/issues/9
